### ISSUE TITLE
microphone text feedback

### ISSUE THREAD

**Issue by RaedsLab** [wit-ai/microphone#11]
A useful feature for debugging purposes is to have microphone.js return in a string the audio input the user just spoke.

**Comment by blandinw** [comment]
You have several ways to go about this:
- look at the WebSocket traffic in Chrome Dev Tool's Network tab
- the `onresult` callback accepts a non-documented third parameter `response`: https://github.com/wit-ai/microphone/blob/master/app/coffee/microphone.coffee#L80

If that helped, please close this issue, thanks!

**Comment by RaedsLab** [comment]
I'm still not sure where to find the plain text string.

**Comment by l5t** [comment]
In the Chrome console, you will find the text in the msg_body field inside the WebSocket tab. See below

![image](https://cloud.githubusercontent.com/assets/6992759/7820497/9fe4765a-039d-11e5-81cc-ef8602737553.png)

**Comment by RaedsLab** [comment]
Very clear, thank you.
