### ISSUE TITLE
How to get the sentence?

### ISSUE THREAD

**Issue by lukesaltweather** [wit-ai/microphone#14]
I can get intent and entities, but how do i get the whole spoken sentence? It can be found in the console, yeah, but how to get it as a variable in the code?

**Comment by l5t** [comment]
There is a 3rd parameter in the onresult function that contains the full response.

**Comment by lukesaltweather** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/19307595/15434422/105f09ce-1eb7-11e6-8b40-fa95b8df356d.png)
But it isn't working.

**Comment by lukesaltweather** [comment]
neither does the callback "response" work

**Comment by l5t** [comment]
```
mic.onresult = function (intent, entities, response) {
         console.log("RESPONSE:", response);
```

will give you the msg_body

```
{msg_id: "2bf9f09f-5add-40ae-9014-877a8a838e5a", msg_body: "wake me up in twenty minutes",...
```

**Comment by lukesaltweather** [comment]
Now there is no as error declared error, but the response is null.
I'm currently using V 0.8.1
Screenshots:
![screenshot_1](https://cloud.githubusercontent.com/assets/19307595/15441331/8d6c6d44-1eda-11e6-894e-2ffa4c364c24.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/19307595/15441332/8d70a774-1eda-11e6-93a9-e912b20f4391.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/19307595/15441333/8d754482-1eda-11e6-946b-e31555ccdb99.png)

**Comment by l5t** [comment]
You need the 3 params in the function even if you don't plan to use intent or entities.
This is what you need
mic.onresult = function (intent, entities, response)

**Comment by lukesaltweather** [comment]
It's working, thanks!

**Comment by shivavelingker** [comment]
The Readme is missing the third argument; it would be helpful if this was included on it
