### ISSUE TITLE
Context flags

### ISSUE THREAD

**Issue by alxferraz** [wit-ai/microphone#16]
How do I manage the conversation context using this example? In node-wit we have an "actions" object and the functions inside this object are called by Wit and you could return flags to update the context. How could I do the same using microphone? Thanks a lot!

**Comment by blandinw** [comment]
@alxferraz see issue #17, microphone.js does not run your Stories.
It only extracts intent and entities, we recommend you generate the bot response yourself, according to extracted intent and entities.
