### ISSUE TITLE
microphone is stuck at "Microphone is connecting"

### ISSUE THREAD

**Issue by Lazizhon** [wit-ai/microphone#18]
Hello.

it only shows "microphone is connecting"

I followed the tutorial from [https://github.com/wit-ai/microphone/blob/master/quickstart.md](quickstart.md).
 
replaced Client token.

browser is  Opera 46 (although I checked it on Chrome and Edge - same issue)  

Using Xampp as a server

**Comment by blandinw** [comment]
@Lazizhon, thank you for your feedback.
Could you please send me your access token by email at my first name @fb.com?

**Comment by blandinw** [comment]
You need to whitelist whatever domain you're using microphone.js from, in your app's settings
This is what the Chrome Network inspector shows:
![image](https://user-images.githubusercontent.com/413070/28142250-e9debebe-6714-11e7-80c2-81fee6279b11.png)

**Comment by elit-altum** [comment]
Hey @blandinw I am encountering a similar issue and Chrome shows a status 101 returned by ```wss://ws.wit.ai/speech_ws``` and it stays on 'Microphone is connecting'. Would you be able to help me out ?

Thank you so much!
