### ISSUE TITLE
Microphone is not ready

### ISSUE THREAD

**Issue by kbenson0616** [wit-ai/microphone#19]
I am a newbie here. I ran the index.html (see attached - saved as a .txt file so I can upload it here).
[index.txt](https://github.com/wit-ai/microphone/files/1128573/index.txt)

that comes with this package.  I get a message that the Microphone is not ready.  I have granted the localhost access to the Microphone. Am I doing something incorrectly?

**Comment by blandinw** [comment]
Have you put in the Wit access token corresponding to your app?
If so, can you please reopen the issue and send your access token by email at my first name @fb.com ?
