### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by shivavelingker** [wit-ai/microphone#23]
This tool is wonderful and works well despite this repo not being updated for a year, but with the response objects, I'm getting another property `WARNING: 'DEPRECATED'` in addition to the valid text-from-speech. Are there any more insights or rationale for this? Despite this repo not being actively maintained, the software still works and is immensely helpful for the work that we're doing, and it would be a shame if we lost access to it.

**Comment by SachinGanesh** [comment]
> This tool is wonderful and works well despite this repo not being updated for a year, but with the response objects, I'm getting another property `WARNING: 'DEPRECATED'` in addition to the valid text-from-speech. Are there any more insights or rationale for this? Despite this repo not being actively maintained, the software still works and is immensely helpful for the work that we're doing, and it would be a shame if we lost access to it.

Yes. Even I'm getting the same warning. I'm planning to use Streaming API in one of my projects. Can we get more clarity on this?

**Comment by jtliao** [comment]
everything will continue to work for the near future
