### ISSUE TITLE
Problem with token ?

### ISSUE THREAD

**Issue by Seraf** [wit-ai/microphone#4]
Hello,

Using the example from the docs (https://wit.ai/docs/web/quickstart) I get a : 

```
Microphone is not connected
Error: Please use a client token when using WebSockets
```

Have you any idea ? I use my wit token and it works with my python library.

Regards

**Comment by nizammazenan** [comment]
Hello,

I using the same tutorial from "https://wit.ai/docs/web/quickstart" and I this error:

Microphone is not connected
Error: Domain "null"is not authorized

What is it means? How to solved it?

thank you

**Comment by l5t** [comment]
https://github.com/wit-ai/microphone/issues/9

**Comment by brendonco** [comment]
it seems the microphone.min.js does not work on IE browser

**Comment by l5t** [comment]
Your browser must support WebRTC, which is the case of Chrome, Firefox and Opera right now. Safari and IE don’t support WebRTC yet. Please refer to this [link](http://caniuse.com/#search=webrtc) for up-to-date information.
