### ISSUE TITLE
Problem with token or ??

### ISSUE THREAD

**Issue by nizammazenan** [wit-ai/microphone#9]
Hello,

I using the same tutorial from "https://wit.ai/docs/web/quickstart" and I get this error:

Microphone is not connected
Error: Domain "null" is not authorized

What is it means? How to solved it?

Another question is, what its mean by:
Allowed Domains: _____</> add new domain name to this instance..____________

What we need to add in the textbox of:"</> add new domain name to this instance..."???

Sorry. I am very beginner, & new student in CS. 

thank you

**Comment by l5t** [comment]
Hi,
when using Microphone, you will need to use the Client Access token and allow your domain to access the API. If your web page is on the foo.com domain, you will have to enter foo.com in the Allowed Domain. Find below an animated gif showing where it is in the Wit Console.
Hope it helps

![clientaccesstoken_and_alloweddomain](https://cloud.githubusercontent.com/assets/6992759/5859806/faea51e8-a211-11e4-9335-68902cb6bc02.gif)

**Comment by nizammazenan** [comment]
Thanks for your reply. 

But I just run the script from localhost & I dont have the domain name like "foo.com" or "lab.wit.ai".

What should I do?

thanks

**Comment by nizammazenan** [comment]
Thanks.. its already solved!

**Comment by arjunrao87** [comment]
@nizammazenan  how was this solved?
